version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: praanacare-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: praanacare
    volumes:
      - mongodb_data:/data/db
      - ./backend/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - praanacare-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: praanacare-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/praanacare?authSource=admin
      JWT_SECRET: your-production-jwt-secret-change-this
      JWT_EXPIRE: 7d
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      BCRYPT_ROUNDS: 12
      RATE_LIMIT_WINDOW: 15
      RATE_LIMIT_MAX: 100
    depends_on:
      - mongodb
    networks:
      - praanacare-network
    volumes:
      - ./backend/uploads:/app/uploads

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: praanacare-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      VITE_API_URL: http://localhost:5000/api
      VITE_WS_URL: http://localhost:5000
    depends_on:
      - backend
    networks:
      - praanacare-network

volumes:
  mongodb_data:

networks:
  praanacare-network:
    driver: bridge
